# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMinimumSize(QtCore.QSize(1920, 1080))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Menu = QtWidgets.QFrame(self.centralwidget)
        self.Menu.setGeometry(QtCore.QRect(0, 0, 1920, 218))
        self.Menu.setStyleSheet("background-color:  rgb(29, 0, 112)")
        self.Menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menu.setObjectName("Menu")
        self.algoTypeBox = QtWidgets.QComboBox(self.Menu)
        self.algoTypeBox.setGeometry(QtCore.QRect(73, 71, 585, 82))
        self.algoTypeBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.algoTypeBox.setStyleSheet("background-color: rgb(173, 0, 255);")
        self.algoTypeBox.setObjectName("algoTypeBox")
        self.AlgoBox = QtWidgets.QComboBox(self.Menu)
        self.AlgoBox.setGeometry(QtCore.QRect(850, 71, 546, 81))
        self.AlgoBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AlgoBox.setStyleSheet("background-color: rgb(173, 0, 255);")
        self.AlgoBox.setObjectName("AlgoBox")
        self.play = QtWidgets.QLabel(self.Menu)
        self.play.setGeometry(QtCore.QRect(1548, 71, 100, 88))
        self.play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play.setText("")
        self.play.setPixmap(QtGui.QPixmap("Assets/play.png"))
        self.play.setScaledContents(True)
        self.play.setObjectName("play")
        self.showCode = QtWidgets.QLabel(self.Menu)
        self.showCode.setGeometry(QtCore.QRect(1800, 71, 94, 88))
        self.showCode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showCode.setText("")
        self.showCode.setPixmap(QtGui.QPixmap("Assets/showCode.png"))
        self.showCode.setScaledContents(True)
        self.showCode.setObjectName("showCode")
        self.code = QtWidgets.QFrame(self.centralwidget)
        self.code.setGeometry(QtCore.QRect(1490, 218, 430, 862))
        self.code.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.code.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.code.setFrameShadow(QtWidgets.QFrame.Raised)
        self.code.setObjectName("code")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
